{
  "swagger": "2.0",
  "host": "localhost:8080",
  "basePath": "/api",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/registrar": {
      "post": {
        "summary": "Registrar usuario con firebase auth",
        "tags": [
          "Registrar"
        ],
        "operationId": "regis",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/regisRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {}
          }
        }
      }
    },
    "/registrarToDb": {
      "post": {
        "summary": "Registrar usuario a firestore",
        "tags": [
          "RegistrarF"
        ],
        "operationId": "regisF",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/regisFRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {}
          }
        }
      }
    },
    "/login": {
      "post": {
        "summary": "Obtener usuario de firebase auth",
        "tags": [
          "Login"
        ],
        "operationId": "login",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/loginRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {}
          }
        }
      }
    },
    "/logout": {
      "get": {
        "summary": "Cerrar Sesion",
        "tags": [
          "Logout"
        ],
        "operationId": "logout",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {}
          }
        }
      }
    },
    "/verifyId": {
      "post": {
        "summary": "Verificar IdToken",
        "tags": [
          "IdToken"
        ],
        "operationId": "IdToken",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/IdTokenRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {}
          }
        }
      }
    },
    "/search": {
      "post": {
        "summary": "Devolver usuario",
        "tags": [
          "getUser"
        ],
        "operationId": "getUser",
        "deprecated": true,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/usergetRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {}
          }
        }
      }
    },
    "/sendRequest": {
      "post": {
        "summary": "Enviar solicitud",
        "tags": [
          "requestUser"
        ],
        "operationId": "requestUser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/requestUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {}
          }
        }
      }
    },
    "/addFriend": {
      "post": {
        "summary": "Agregar a usuario",
        "tags": [
          "addUser"
        ],
        "operationId": "addUser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/addUser"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {}
          }
        }
      }
    },
    "/getFriend": {
      "post": {
        "summary": "Recibir amigos",
        "tags": [
          "getFriend"
        ],
        "operationId": "getFriend",
        "deprecated": true,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/getFriend"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {}
          }
        }
      }
    },
    "/enviarMsg": {
      "post": {
        "summary": "Enviar Mensaje",
        "tags": [
          "enviarMsg"
        ],
        "operationId": "sendMsg",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/sendMsg"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "regisRequest": {
      "title": "regisRequest",
      "example": {
        "displayName": "locksly011",
        "email": "abc@xyz.com",
        "password": "abc@123",
        "profilePic": ""
      },
      "type": "object",
      "properties": {
        "displayName": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "profilePic": {
          "type": "string"
        }
      },
      "required": [
        "displayName",
        "email",
        "password",
        "profilePic"
      ]
    },
    "regisFRequest": {
      "title": "regisFRequest",
      "example": {
        "userName": "locksly011",
        "email": "abc@xyz.com",
        "uid": "uid"
      },
      "type": "object",
      "properties": {
        "userName": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "uid": {
          "type": "string"
        }
      },
      "required": [
        "userName",
        "email",
        "uid"
      ]
    },
    "loginRequest": {
      "title": "loginRequest",
      "example": {
        "email": "abc@xyz.com",
        "password": "abc@123"
      },
      "type": "object",
      "properties": {
        "email": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "email",
        "password"
      ]
    },
    "IdTokenRequest": {
      "title": "IdTokenRequest",
      "example": {
        "IdToken": "eyJhbGciOiJSUzI1NiIsImtpZCI6IjBiYmQyOTllODU2MmU3MmYyZThkN2YwMTliYTdiZjAxMWFlZjU1Y2EiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vYmxhc2UtYzc2YTIiLCJhdWQiOiJibGFzZS1jNzZhMiIsImF1dGhfdGltZSI6MTcwMTE5NjUxNywidXNlcl9pZCI6IjFZNFZSOFR0UlpWUmNJVG1qclNnNWVzU3I4NzMiLCJzdWIiOiIxWTRWUjhUdFJaVlJjSVRtanJTZzVlc1NyODczIiwiaWF0IjoxNzAxMTk2NTE3LCJleHAiOjE3MDEyMDAxMTcsImVtYWlsIjoiYWJjQHh5ei5jb20iLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsImZpcmViYXNlIjp7ImlkZW50aXRpZXMiOnsiZW1haWwiOlsiYWJjQHh5ei5jb20iXX0sInNpZ25faW5fcHJvdmlkZXIiOiJwYXNzd29yZCJ9fQ.cGbVc2OEA2y6JIVj5q6ODOyxfo2nHO3wp99rU5RzU33pD28kqo-kaevbRO0fQbICVzxmjrmFR1g4j08zyDqir8W4jbKrC2mdXlKQnvJcewC-fZZ2v5kLu0PdsgPEylVhep_yW-KY3NyhXfNnO5JY3LStKNJLKX2Y1xWpoSaV4p5ziJ3UmYqZORYFOIJeT80g1bgAoNvBNBAwK_LLYyyLwKAcKhNPbxsXdFBgmu0czqcTOYFF_7ydEeD-oA7eBIqn1fjw9fEN6qZaP9LnPDZEokI_ySum4rK1KFkEjYrVLOWdekisOiR34hPwvJFf0Q1zM1kISTrFeu6ADhEGDaNFFg"
      },
      "type": "object",
      "properties": {
        "IdToken": {
          "type": "string"
        }
      },
      "required": [
        "IdToken"
      ]
    },
    "usergetRequest": {
      "title": "usergetRequest",
      "example": {
        "userId": "aEgDvbhpsPecfAGsZ5KFeEF5TCA3",
        "friendName": "Wil011"
      },
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "friendName": {
          "type": "string"
        }
      },
      "required": [
        "userId",
        "friendName"
      ]
    },
    "requestUser": {
      "title": "requestUser",
      "example": {
        "userId": "aEgDvbhpsPecfAGsZ5KFeEF5TCA3",
        "userIdF": "nKO4ZHXIwrUpm83cEgSQhQGVJEe2"
      },
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "userIdF": {
          "type": "string"
        }
      },
      "required": [
        "userId",
        "userIdF"
      ]
    },
    "addUser": {
      "title": "addUser",
      "example": {
        "userId": "aEgDvbhpsPecfAGsZ5KFeEF5TCA3",
        "displayName": "fulano",
        "email": "abc@xyz.com",
        "profilePic": "",
        "userIdF": "nKO4ZHXIwrUpm83cEgSQhQGVJEe2",
        "displayNameF": "fulano",
        "emailF": "abc@xyz.com",
        "profilePicF": ""
      },
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "displayName": {
          "type": "string"
        },
        "profilePic": {
          "type": "string"
        },
        "userIdF": {
          "type": "string"
        },
        "emailF": {
          "type": "string"
        },
        "displayNameF": {
          "type": "string"
        },
        "profilePicF": {
          "type": "string"
        }
      },
      "required": [
        "userId",
        "displayName",
        "email",
        "profilePic",
        "userIdF",
        "displayNameF",
        "emailF",
        "profilePicF"
      ]
    },
    "getFriend": {
      "title": "getFriend",
      "example": {
        "userId": "idJETJxQrZXnvjAkPBfK9vTgggB2"
      },
      "type": "object",
      "properties": {
        "userId": {
          "type": "string"
        }
      },
      "required": [
        "userId"
      ]
    },
    "sendMsg": {
      "title": "sendMsg",
      "example": {
        "chatId": "08c87d64-e7ae-4c5c-b488-17cd3c824129",
        "emisor": "dsrWvwPRGYNM0EfKDhGU7uW4Kex2",
        "fecha": "102040",
        "mensaje": "Mensaje",
        "orden": "16656000",
        "visto": "false",
        "mensajeResp": "Respuesta",
        "fileName": "Documento",
        "url": "url"
      },
      "type": "object",
      "properties": {
        "chatId": {
          "type": "string"
        },
        "emisor": {
          "type": "string"
        },
        "fecha": {
          "type": "string"
        },
        "mensaje": {
          "type": "string"
        },
        "orden": {
          "type": "string"
        },
        "visto": {
          "type": "boolean"
        },
        "mensajeResp": {
          "type": "string"
        },
        "fileName": {
          "type": "string"
        },
        "url": {
          "type": "string"
        }
      },
      "required": [
        "chatId",
        "emisor",
        "fecha",
        "mensaje",
        "orden",
        "visto",
        "mensajeResp",
        "fileName",
        "url"
      ]
    }
  }
}